fullnameOverride: ''
nameOverride: ''

dockerRegistry: docker.io
dockerTag: latest

vault:
  enabled: false
  secretRefreshInterval: '12h'
  secretStoreKind: ClusterSecretStore
  secretKeyPrefix: ''
  environment: ''

configs: {}

secrets: {}

apps: {}
